### ISSUE TITLE
Decrease amount of method calls.

### ISSUE THREAD

**Issue by xinonghost** [Mykola2/CoinsDiffusion#2]
We can put this line: https://github.com/Mykola2/CoinsDiffusion/blob/master/src/main/java/org/training/diffusion/Main.java#L44 into this call function: https://github.com/Mykola2/CoinsDiffusion/blob/master/src/main/java/org/training/diffusion/Main.java#L29 and there will no need to call read line method once more: https://github.com/Mykola2/CoinsDiffusion/blob/master/src/main/java/org/training/diffusion/Main.java#L28

**Comment by Mykola2** [comment]
done https://github.com/Mykola2/CoinsDiffusion/commit/7d49026b56e2f0d4ef56eddba290ef50e5197235
