### ISSUE TITLE
https://github.com/Mykola2/CoinsDiffusion/blob/master/src/main/java/org/training/diffusion/Main.java#L40

### ISSUE THREAD

**Issue by xinonghost** [Mykola2/CoinsDiffusion#3]
Maybe it will be better if we put this:
```
String name = params[0];
int lX = Integer.parseInt(params[1]);
int lY = Integer.parseInt(params[2]);
int hX = Integer.parseInt(params[3]);
int hY = Integer.parseInt(params[4]);
```
into "addCountry" method call without creation of auxiliary variables?

**Comment by Mykola2** [comment]
and it will be 158 symbols in [L40](https://github.com/Mykola2/CoinsDiffusion/blob/master/src/main/java/org/training/diffusion/Main.java#L40)

**Comment by xinonghost** [comment]
You can brake one long list of params into several lines.
