### ISSUE TITLE
Days in the city

### ISSUE THREAD

**Issue by Rommanski** [Mykola2/CoinsDiffusion#6]
I think that better place for this [variable](https://github.com/Mykola2/CoinsDiffusion/blob/master/src/main/java/org/training/diffusion/model/Country.java#L16) will be [World](https://github.com/Mykola2/CoinsDiffusion/blob/master/src/main/java/org/training/diffusion/model/World.java) model. We have same day fro every country and cities.

**Comment by Mykola2** [comment]
This approach helps us to know, when country is complete.
